# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-23 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180723_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radios',
            old_name='Date',
            new_name='DateCreation',
        ),
    ]
